
//LOGIN
export const CHANGE_LOGIN_DATA = 'CHANGE_LOGIN_DATA';
export const TOGGLE_SHOW_PASSWORD_LOGIN = 'SHOW_PASSWORD_LOGIN';
export const CLEAR_ERRORS_LOGIN = 'CLEAR_ERRORS_LOGIN';

//SIGNUP
export const CHANGE_SIGNUP_DATA = 'CHANGE_SIGNUP_DATA';
export const TOGGLE_SHOW_PASSWORD_SIGNUP = 'TOGGLE_SHOW_PASSWORD_SIGNUP';
export const ON_FILE_CHANGE_SIGNUP = 'ON_FILE_CHANGE_SIGNUP';
export const CLEAR_ERRORS_SIGNUP = 'CLEAR_ERRORS_SIGNUP';

//pass
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const TOGGLE_PASS_PASSWORD = 'TOGGLE_PASS_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const CLEAR_ERRORS_RESET_PASSWORD = 'CLEAR_ERRORS_RESET_PASSWORD';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const CLEAR_ERRORS_CHANGE_PASSWORD = 'CLEAR_ERRORS_CHANGE_PASSWORD';

//myaccount
export const CHANGE_MYACCOUNT_DATA = 'CHANGE_MYACCOUNT_DATA';
export const TOGGLE_CHANGEPASS_MODAL = 'TOGGLE_CHANGEPASS_MODAL';
export const UPDATE_MERCHANT_DATA = 'UPDATE_MERCHANT_DATA';
export const INITIALIZE_MYACCOUNT_DATA = 'INITIALIZE_MYACCOUNT_DATA';

//payment-details
export const CHANGE_PAYMENTDETAILS_DATA = 'CHANGE_PAYMENTDETAILS_DATA';
export const TOGGLE_PAYMENT_DETAILS_FORM = 'TOGGLE_PAYMENT_DETAILS_FORM';
export const CHANGE_PAYMENTD_SELECT_LABELWIDTH = 'CHANGE_PAYMENTD_SELECT_LABELWIDTH';
export const CLEAR_ERRORS_PAYMENT_DETAILS = 'CLEAR_ERRORS_PAYMENT_DETAILS';



//POP-UPS;
export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';
export const TOGGLE_LOADING_MODAL = 'TOGGLE_LOADING_MODAL';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const TOGGLE_POPOUT_LOGOUT = 'TOGGLE_POPOUT_LOGOUT';
export const TOGGLE_NAVUP = 'TOGGLE_NAVUP';
export const TOGGLE_VARIANT_MODAL = 'TOGGLE_VARIANT_MODAL';
export const TOGGLE_ADD_IMAGE_MODAL = 'TOGGLE_ADD_IMAGE_MODAL';



//REPORTS
export const GET_MONTHLY_REPORT_DATA = 'GET_MONTHLY_REPORT_DATA';
export const GET_PRODUCT_INVENTORY_REPORT_DATA = 'GET_PRODUCT_INVENTORY_REPORT_DATA';
export const GET_MONTHLY_SALES_REPORT_DATA = 'GET_MONTHLY_SALES_REPORT_DATA';
export const GET_DAILY_SALES_REPORT_DATA = 'GET_DAILY_SALES_REPORT_DATA';
export const CHANGE_DATE_REPORT = 'CHANGE_DATE_REPORT';
export const DAILY = 'DAILY';
export const MONTHLY = 'MONTHLY';


//Dashboard
export const UPDATE_DASHBOARD_DATA = 'UPDATE_DASHBOARD_DATA';
export const UPDATE_ORDER_EARNINGS = 'UPDATE_ORDER_EARNINGS';



//Add Product 
export const CHANGE_ADD_PRODUCT_DATA = 'CHANGE_ADD_PRODUCT_DATA';
export const CHANGE_ADD_PRODUCT_SELECT_LABELWIDTH = 'CHANGE_ADD_PRODUCT_SELECT_LABELWIDTH';
export const CLEAR_ERRORS_ADD_PRODUCT = 'CLEAR_ERRORS_ADD_PRODUCT';
export const DELETE_TAG_ADD_PRODUCT = 'DELETE_TAG_ADD_PRODUCT';
export const ADD_TAG_ADD_PRODUCT = 'ADD_TAG_ADD_PRODUCT';
export const CLEAR_OPTIONS = 'CLEAR_OPTIONS';

//Hooks
export const CHANGE_FILE = 'CHANGE_FILE';
export const ADD_UPLOAD_BTN = 'ADD_UPLOAD_BTN';
export const TOGGLE_ADD_BTN = 'TOGGLE_ADD_BTN';
export const REMOVE_UPLOAD_BTN = 'REMOVE_UPLOAD_BTN';
export const TOGGLE_ADD_OPTIONS = 'TOGGLE_ADD_OPTIONS';
export const SET_LABEL_WIDTH = 'SET_LABEL_WIDTH';
export const CLEAR_FILES = 'CLEAR_FILES';

//Edit Product
export const CHANGE_EDIT_PRODUCT_DATA = 'CHANGE_EDIT_PRODUCT_DATA';
export const CHANGE_EDIT_PRODUCT_SELECT_LABELWIDTH = 'CHANGE_EDIT_PRODUCT_SELECT_LABELWIDTH';
export const UPDATE_CURRENT_EDIT_PRODUCT_DETAILS = 'UPDATE_CURRENT_EDIT_PRODUCT_DETAILS';
export const DELETE_TAG_EDIT_PRODUCT = 'DELETE_TAG_EDIT_PRODUCT';
export const ADD_TAG_EDIT_PRODUCT = 'ADD_TAG_EDIT_PRODUCT';
export const CLEAR_ERRORS_EDIT_PRODUCT = 'CLEAR_ERRORS_EDIT_PRODUCT';

//Profile Images
export const UPDATE_BANNER = 'UPDATE_BANNER';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const INITIALIZE_IMAGES_PATHS = 'INITIALIZE_IMAGES_PATHS';





//Products 
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const UPDATE_CURRENT_PRODUCTS = 'UPDATE_CURRENT_PRODUCTS';
export const UPDATE_PRODUCT_DETAILS = 'UPDATE_PRODUCT_DETAILS';
export const CHANGE_VARIANT_DATA = 'CHANGE_VARIANT_DATA';
export const UPDATE_PRODUCT_VARIANT = 'UPDATE_PRODUCT_VARIANT';
export const UPDATE_IMAGES_DETAILS = 'UPDATE_IMAGES_DETAILS';

//ORDERS
export const UPDATE_CURRENT_ORDERS = 'UPDATE_CURRENT_ORDERS';
export const UPDATE_CURRENT_ORDER_EARNINGS = 'UPDATE_CURRENT_ORDER_EARNINGS';
export const UPDATE_ORDER_DETAILS = 'UPDATE_ORDER_DETAILS';
export const UPDATE_ORDER_INVOICE_DATA = 'UPDATE_ORDER_INVOICE_DATA';



//Add Options
export const ADD_OPTION_ON_SELECT_CHANGE = 'ADD_OPTION_ON_SELECT_CHANGE';
export const ADD_ANOTHER_OPTION = 'ADD_ANOTHER_OPTION';
export const TOGGLE_ADD_ANOTHER_OPTION_BTN = 'TOGGLE_ADD_ANOTHER_OPTION_BTN';
export const REMOVE_ANOTHER_OPTION = 'REMOVE_ANOTHER_OPTION';

//Add Option Select
export const TOGGLE_INPUT_FIELD = 'TOGGLE_INPUT_FIELD';
export const UPDATE_VALUE = 'UPDATE_VALUE';



export const TOGGLE_UI_THEME = 'TOGGLE_UI_THEME';

export const LOGOUT_USER = 'LOGOUT_USER';

export const RESET = 'RESET';

export const AUTH_LOGIN = 'AUTH_LOGIN';

export const CHANGE_DATE = 'CHANGE_DATE';

export const RECEIVED_TOTAL_SALE = 'RECEIVED_TOTAL_SALE';

export const LOGIN_VALIDATION = 'LOGIN_VALIDATION';

export const EDIT_INFO = 'EDIT_INFO';


export const TOGGLE_ALERT = 'TOGGLE_ALERT';

export const SHOW_EDIT = 'SHOW_EDIT';




export const REGISTER_MERCHANT = 'REGISTER_MERCHANT';



export const TOGGLE_IS_APP_MOUNTED = 'TOGGLE_IS_APP_MOUNTED';

export const REQUEST_CURRENT_PRODUCTS = 'REQUEST_CURRENT_PRODUCTS';

export const GET_RECENT_ORDERS = 'GET_RECENT_ORDERS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';




